<a href="https://colab.research.google.com/github/SaketMunda/tensorflow-fundamentals/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number

2.9.2


## What are Tensors ?

You can think of tensors as a multi-dimensional numercial representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:

* It could be numbers themselves (using tensors to represent the price of houses).
* It could be an image (using tensors to represent the pixels of an image).
* It could be text (using tensors to represent words).
* Or it could be some other form of information (or data) you want to represent with numbers.

The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs and TPUs.

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representation of our data, we can generally find them faster using GPUs and TPUs.

### Creating Tensors with `tf.constant()`

In [3]:
# create a scalar (rank 0 tensors)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

here notice that shape is empty, it means it has no dimensions, it's just a number

In [4]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# create a vector (more than 0 dimensions)
vector = tf.constant([2,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [6]:
# check the dimension 
vector.ndim

1

it says, it has 1 dimension

In [7]:
# let's create a matrix
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

check the value of shape this time, it has 2 numbers which means this is a 2 dimensional tensor constant

In [8]:
# checking the ndim
matrix.ndim

2

by default if we don't pass any dtype value while creating constant tensor it'll create int32 or float32 tensors

This is also called 32-bit precision(the higher the number, the more precise the number, the more space it takes up on your computer).

In [9]:
# create another matrix and define the datatype
another_matrix = tf.constant([[1.,2.],
                              [2.,3.],
                              [4.,5.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 3.],
       [4., 5.]], dtype=float16)>

In [10]:
# even though another_matrix contains the more numbers, its dimensions stay the same
another_matrix.ndim

2

In [11]:
# How about a tensor ? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### Creating tensors with `tf.Variable()`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using `tf.Variable()`

The difference between `tf.constant()` and `tf.Variable()` is tensors with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).

In [13]:
# create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Now let's try to change one of the elements of the changeable tensor

In [14]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

To change an element of a `tf.Variable()` tensor requires the `assign()` method

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Now let's try to change a value in unchangeable tensor i.e `tf.constant()`

In [16]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

Why would you want to create random tensors ?

This is what neural networks use to initialize their weights (patterns) that they're trying to learn in the data.

We can create random tensors by using the `tf.random.Generator` class

In [17]:
# create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

The random tensors we've made are actually pseudorandom numbers (they appear as random, but really aren't)

In [18]:
# create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(7)
random_4 = random_4.normal(shape=(3,2))

# check the tensors and see if they are equal
random_3, random_4, random_3 == random_4, random_1==random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of a Tensor

Why we want to shuffle the order of a tensor ?

Let's say you working with 15K images of cats and dogs and the first 10K images are of cats and the next 5K were of dogs. This order could effect how a neural network leanrs (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [19]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [20]:
# Shuffle in the same order every time using the same parameter (won't actually be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

But even if we set the random seed value, everytime when we run it returns different order. Why ?

It's due to rule #4 of the [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) documentation

> Rule 4: If the global and the operation seed are set: Both seeds are used in conjuction to determine the random sequence.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [21]:
# Shuffle in the same order every time

# set the global seed
tf.random.set_seed(42)

# set the operational seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
# set the global random seed
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled)

# this way also it can reproduce same results

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [23]:
# Make a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Make a tensor of all zeroes
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Creating Tensors from Numpy arrays

> 🔑 **Note:** A matrix or tensor is typically represented by a capital letter (eg. `X` or `A`) where as a vector is typically represent by a lowercase letter (eg. `y` or `b`)

In [25]:
import numpy as np
numpy_A = np.arange(1,29,dtype=np.int32) # create a NumPy array betweem 1 and 29
numpy_A, numpy_A.size

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int32), 28)

In [26]:
tf.constant(numpy_A, shape=(2,2,7)) 

# note : the shape total (2,2,7) has to match the number of elements in the array i.e 28

<tf.Tensor: shape=(2, 2, 7), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]]], dtype=int32)>

### Getting information from tensors

* Shape: The length (number of elements) of each of the dimensions of a tensor
* Size: The total number of items in the tensor
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.

In [27]:
# Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, tf.size(rank_4_tensor), rank_4_tensor.ndim,  tf.rank(rank_4_tensor)

(TensorShape([2, 3, 4, 5]),
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [29]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype.name)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[1])
print("Total number of elements in tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: float32
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 3
Total number of elements in tensor: 120


### Indexing in Tensors

We can index tensors just like Python Lists.

In [30]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Adding dimensions to the existing tensor

We can also add dimensions to our tensor whilst keeping the same information present using below methods,

* `tf.newaxis`
* `tf.expand_dims()`

In [32]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([
                              
                                [10,7],
                                [3,4]
                              
                            ])
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [33]:
# now add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[...,tf.newaxis] # in python "..." means "all dimensions prior to"
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# using tf.expand_dims() at the beginnning
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (tensor operations)

Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.


#### 1. Basic Operations

`+`, `-`, `*`, `/`

In [35]:
# adding values to a tensor using the addition operator
tensor = tf.constant([[2,4],
                      [5,6]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [15, 16]], dtype=int32)>

In [36]:
# since we used constant tensors, the original tensor is unchanges
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [37]:
# other operators
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -6],
       [-5, -4]], dtype=int32)>

In [38]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [50, 60]], dtype=int32)>

In [39]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.4],
       [0.5, 0.6]])>

We can also use the equivalent TensorFlow function. Using the TensorFlow function (where possible) has the advantage of being speed up later down the line when running as part of a [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs)

In [40]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [50, 60]], dtype=int32)>

#### 2. Matrix Multiplication

One of the most common operations in machine learning algorithms is Matrix Multiplication

TensorFlow implements this matric multiplication functionality in the `tf.matmul()` method.

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match
- it means [3,`2`] @ [`3`,3], here the highlighted dimensions should match, in this example multiplication is not possible.
- [3,`2`] @ [`2`,3], this will work

2. The resulting matrix has the shape of the outer dimensions.
- it means [`3`,2] @ [2,`3`], result would be [`3`,`3`]

> 🔑 **Note** : `@` in Python, is the symbol of matrix multiplication.

In [41]:
# Matrix multiplication in TensorFlow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 32],
       [40, 56]], dtype=int32)>

In [42]:
# matrix multiplication with Python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 32],
       [40, 56]], dtype=int32)>

Both of these worked because the shape of our Tensors were identical,

Let's try if the shape is mis-matched

In [43]:
# create (3,2) tensor
X = tf.constant([[1,2,3],
                 [4,5,6]])

# create another (3,2) tensor
Y = tf.constant([[7,8,9],
                 [10,11,12]])

X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [44]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

We're violating the first rule, which means the inner dimensions of two tensors must be same to be multiplied.

So, now let's make it, and make the second tensor fit for multiplication using reshaping it.

In [46]:
# reshape the tensor
print(tf.reshape(Y, shape=(3,2)))

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [47]:
# let's multiple now
tf.matmul(X, tf.reshape(Y, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

We might have produced the result of multiplication, but notice `tf.reshape` has changed the order of the tensor, so instead we will use Transposing the tensor

In [48]:
# let's transpose and see
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [49]:
# and then try the multiplication
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

Voila ! See the difference in the result

There's one more way to perform matrix multiplication in TensorFlow is using `tf.tensordot()`

In [50]:
# perform the dot product on X and Y
tf.tensordot(X, tf.transpose(Y), axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

#### Changing the datatype of the tensor

Sometimes you'll want to alter the default datatype of your tensor.

This is common when you want to compute using less precision (eg 16-bit floating point numbers vs 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bit, the less space the computations require).

We can change the datatype of a tensor using `tf.cast()`

In [51]:
# Create a tensor with default datatype (float32)
B = tf.constant([1.7,1.4])

# Create a tensor with default datatype (int32)
C = tf.constant([7,4])

B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 1.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [52]:
# now let's cast and reduce the precision of both
B = tf.cast(B, dtype=tf.float16)

C = tf.cast(C, dtype=tf.int16)

B,C

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([7, 4], dtype=int16)>)

#### Getting the absolute value

Sometimes you'll want the absolute values (all values are positive) of elements in your tensors


To do so, you can use `tf.abs()`

In [53]:
# create tensor with negative values
D = tf.constant([-4, -7])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-4, -7], dtype=int32)>

In [54]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

#### Aggregation Functions for Tensors (find min, max, mean and more)

We can quickly aggregate(perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.


To do so, aggregation methods typically have the syntax `reduce_[action]`, such as:

* `tf.reduce_max()`
* `tf.reduce_min()`
* `tf.reduce_mean()`
* `tf.reduce_sum()`
* `tf.math.reduce_std()` <------------|Some functions needed to be use with 
* `tf.math.reduce_variance()` <---|`math` then followed by the function

> 🔑 **Note**: Typically, each of these functions are under the `math` module, eg. `tf.math.reduce_min()` but we can use the alias `tf.reduce_min()`

In [55]:
# Create tensor with 50 random values between 0 and 100
tf.random.set_seed(42)
E = tf.random.uniform(shape = (50,),minval=0, maxval=1)
# we can use this as well, tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [56]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [57]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [58]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.513808>

In [59]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=float32, numpy=25.690401>

In [60]:
# Find the standard deviation
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.2664255>

In [61]:
# Find the variance
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.070982546>

#### Find the positional maximum and minimum

How about finding the position a tensor where the maximum value occurs ?

This is helpful when you want to line up your lables (say `['Green','Blue','Red']`) with your prediction probabilites tensor (eg `[0.98, 0.01, 0.01]`)

In this case, the predicted label (the one with the highest prediction probability) would be `Green`

You can do the same for the minimum(if required) with the following:

* `tf.argmax()` - find the position of the maximum element in a given tensor
* `tf.argmin()` - find the position of the minimum element in a given tensor

In [63]:
# so taking the same tensor from above
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [66]:
# Find the maximum element in a given tensor
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [67]:
# extended to find the position
tf.argmax(E).numpy()

42

In [73]:
# let's whether it's correct or not
(tf.reduce_max(E).numpy() ==  E[tf.argmax(E).numpy()]).numpy()

True

In [75]:
# Find the minimum element in a given tensor
tf.argmin(E), tf.reduce_min(E), E[tf.argmin(E)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

#### Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use `tf.squeeze()`

In [76]:
# Create a 5 dimension tensor of 50 numbers between 0 and 100

F = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))

F.shape, F.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [77]:
F_squeezed = tf.squeeze(F)

In [79]:
F_squeezed.shape, F_squeezed.ndim

(TensorShape([50]), 1)

#### One Hot Encoding

If you have a tensor of indices and would like to one-hot encode it, you can use `tf.one_hot()` - Basically Numerical encoding

Specify `depth` parameter (the level which you want to one-hot encode to).

In [81]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [84]:
# We can also specify instead of 0 and 1, using on_value and off_value
tf.one_hot(some_list, depth = 5, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'No', b'Yes', b'No']], dtype=object)>

#### Some more math functions

* `tf.square()`
* `tf.math.log()`
* `tf.sqrt()`

In [85]:
# Create a tensor
G = tf.constant(np.arange(1,10))
G

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [86]:
# Squaring
tf.square(G)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [89]:
# Log - it takes only non-integer
tf.math.log(tf.cast(G, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [91]:
# Square root - it takes only non-integer
tf.sqrt(tf.cast(G, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

### Tensors and Numpy

We've seen some examples of tensors interact with Numpy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using,

* np.array()
* tensor.numpy()

In [93]:
# Create a tensor using Numpy array
H = tf.constant(np.array([3.,6.,9.]))
H

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 6., 9.])>

In [95]:
# Convert the H tensor into numpy using np.array()
np.array(H), type(np.array(H))

(array([3., 6., 9.]), numpy.ndarray)

In [96]:
# Convert the H tensor into numpy using tensor.numpy()
H.numpy(), type(H.numpy())

(array([3., 6., 9.]), numpy.ndarray)

By Default tensors have `float32` dtype whereas Numpy arrays have `float64`

This is because neural networks can generally work very well with less precision (32-bit rather than 64-bit)

In [97]:
# Create a tensor from Numpy and from an array
numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)