<a href="https://colab.research.google.com/github/SaketMunda/tensorflow-fundamentals/blob/master/00_tensorflow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises for TensorFlow Fundamentals

In [1]:
# first importing the tensorflow and checking the version of tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


## 1. Create vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

### Vector

In [3]:
# Create a vector tensor, more than 0 dimension
vector = tf.constant([2,7])

In [4]:
vector, vector.ndim # shape is 2, and dimension is 1

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>, 1)

### Scalar

In [7]:
# Create a scalar tensor, 0 dimension
scalar = tf.constant(1)

In [8]:
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

### Matrix

In [9]:
# create a matrix, more than 1 dimension
matrix = tf.constant([[1,2]])

In [10]:
matrix, matrix.ndim

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>, 2)

### Tensor

In [11]:
# create a tensor, more than 2 dimension, although everything that created above are technically tensors
tensor = tf.constant([[[1,2],[3,4]]])

In [12]:
tensor, tensor.ndim

(<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]]], dtype=int32)>, 3)

## 2. Find the shape, rank and size of the tensors created in 1.

In [20]:
# scalar
scalar.shape, tf.rank(scalar), tf.size(scalar)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [21]:
# vector
vector.shape, tf.rank(vector), tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [22]:
# matrix
matrix.shape, tf.rank(matrix), tf.size(matrix)

(TensorShape([1, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [25]:
# tensor
tensor.shape, tf.rank(tensor).numpy(), tf.size(tensor).numpy()

(TensorShape([1, 2, 2]), 3, 4)

## 3. Create two tensor containing random values between 0 and 1 with shape [5, 300]

In [35]:
tensor_1 = tf.random.uniform(shape=(5,300), maxval=1)

In [34]:
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.5495442 , 0.9071908 , 0.01839256, ..., 0.18767607, 0.17765498,
        0.744344  ],
       [0.9408431 , 0.13851082, 0.7633331 , ..., 0.9895227 , 0.63504386,
        0.86147666],
       [0.73433375, 0.37296772, 0.03594434, ..., 0.5366154 , 0.8264357 ,
        0.69718266],
       [0.45012665, 0.9502078 , 0.9503919 , ..., 0.04277134, 0.81989443,
        0.7635082 ],
       [0.3662908 , 0.5243217 , 0.85867643, ..., 0.21819413, 0.47386515,
        0.99849784]], dtype=float32)>

In [36]:
tensor_2 = tf.random.uniform(shape=[5,300], maxval=1)

In [37]:
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.82825184, 0.6818149 , 0.02262032, ..., 0.84771204, 0.5946971 ,
        0.19516253],
       [0.95749664, 0.34489667, 0.18324673, ..., 0.7432481 , 0.8610915 ,
        0.393003  ],
       [0.5458158 , 0.26161885, 0.507807  , ..., 0.5696775 , 0.32474804,
        0.5702914 ],
       [0.9964615 , 0.39158046, 0.5731878 , ..., 0.6864072 , 0.50981367,
        0.5920334 ],
       [0.7110044 , 0.50321245, 0.8187568 , ..., 0.11610651, 0.08147061,
        0.25464153]], dtype=float32)>

## 4. Multiply the two tensors you created in 3 using matrix multiplication

In [40]:
multiplication = tf.matmul(tensor_1, tensor_2, transpose_b=True)

In [41]:
multiplication , multiplication.ndim

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[75.934204, 74.09201 , 78.10324 , 73.8513  , 71.79252 ],
        [79.42161 , 77.88776 , 78.816315, 76.94847 , 73.15262 ],
        [76.85294 , 73.534996, 76.012115, 72.37041 , 71.52866 ],
        [76.227646, 78.47322 , 81.315445, 78.55235 , 75.24794 ],
        [80.37782 , 77.07042 , 81.76574 , 76.511185, 75.3479  ]],
       dtype=float32)>, 2)

## 5. Multiply the two tensors you created in 3 using dot product

In [47]:
dot = tf.tensordot(tensor_1, tensor_2, axes=0)

In [48]:
dot.ndim, dot.shape

(4, TensorShape([5, 300, 5, 300]))

## 6. Create a tensor with random values between 0 and 1 with shape [224,224,3]

In [49]:
tensor_random = tf.random.uniform(shape=(224,224,3), maxval=1)

## 7. Find the min and max values of the tensor you created in 6 along the first axis

In [54]:
# max
tf.reduce_max(tensor_random)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999976>

In [55]:
# min
tf.reduce_min(tensor_random)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [56]:
tensor_random_1 = tf.random.uniform(shape=(1,224,224,3), maxval=1)

In [57]:
tensor_random_1.shape

TensorShape([1, 224, 224, 3])

In [58]:
tensor_random_1_squeezed = tf.squeeze(tensor_random_1)

In [60]:
tensor_random_1_squeezed.shape

TensorShape([224, 224, 3])

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [61]:
tensor_random_2 = tf.random.uniform(shape=[10], maxval=10)

In [63]:
tf.argmax(tensor_random_2)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [64]:
tensor_random_2

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.7337956, 1.0498857, 7.3592863, 2.4113512, 9.840231 , 1.7864108,
       3.7696218, 4.4807696, 6.8424034, 2.4963987], dtype=float32)>

## 10. One-hot encode the tensor you created in 9

In [65]:
tf.one_hot(tensor_random_2, depth=10)

InvalidArgumentError: ignored

In [78]:
tf_1 = tf.random.uniform(shape=[10], maxval=10, dtype= tf.int32)

In [79]:
tf_1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 5, 0, 4, 1, 8, 3, 9, 0, 6], dtype=int32)>

In [81]:
tf.one_hot(tf_1, depth = 10, on_value="Yes", off_value="No")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'No', b'Yes', b'No', b'No', b'No', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'Yes', b'No', b'No', b'No',
        b'No'],
       [b'Yes', b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'No', b'No', b'No', b'Yes', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'Yes', b'No', b'No', b'No', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'Yes',
        b'No'],
       [b'No', b'No', b'No', b'Yes', b'No', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'No',
        b'Yes'],
       [b'Yes', b'No', b'No', b'No', b'No', b'No', b'No', b'No', b'No',
        b'No'],
       [b'No', b'No', b'No', b'No', b'No', b'No', b'Yes', b'No', b'No',
        b'No']], dtype=object)>